cursor_shape          Underline
cursor_underline_thickness 1
window_padding_width  20

# Special
foreground #FFFFFF
background #1E1F27

# Black
color0 #1F2229
color8 #198388

# Red
color1 #D41919
color9 #EC0101

# Green
color2  #5EBDAB
color10 #47D4B9

# Yellow
color3  #FEA44C
color11 #FF8A18

# Blue
color4  #367BF0
color12 #277FFF

# Magenta
color5  #9755B3
color13 #962AC3

# Cyan
color6  #49AEE6
color14 #05A1F7

# White
color7  #E6E6E6
color15 #FFFFFF

# Cursor
cursor #c0caf5
cursor_text_color #1a1b26

# Selection highlight
selection_foreground #7aa2f7
selection_background #28344a
