#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

~/.config/polybar/./launch.sh
feh --bg-fill /home/vidikali/DATOS/fotos/fondo\ pantalla/montaña\ negra.jpg
bspc config focus_follows_pointer true
picom --experimental-backends &
bspc config border_width 0
xsetroot -cursor_name left_ptr &

#mouse
xinput set-prop 'SynPS/2 Synaptics TouchPad' 'libinput Natural Scrolling Enabled' 1
xinput --set-prop 'SynPS/2 Synaptics TouchPad' 'libinput Accel Speed' 0.30
xinput set-prop 'Newmen USB Gaming Mouse MX510F' 'libinput Accel Speed' -0.5

#monitor
if [[ $(xrandr -q | grep 'DP-2 connected') ]]; then
    xrandr --output DP-2 --primary --mode 1360x768 --rotate normal --output eDP-1 --mode 1920x1080 --rotate normal --right-of DP-2

	bspc monitor DP-2 -d 1 2 3 4 5
	bspc monitor eDP-1 -d 6 7 8 9 0
fi




